"""LaTeX + .bib bundle generator (M10 / ADR-0016).

Output is a zip containing two files:
- ``references.bib`` — produced by ``paper_rag.tools.bibtex_export`` (reused
  unchanged from M6 #31)
- ``related_work.tex`` — a single paragraph using ``\\cite{key}`` syntax,
  ready to ``\\input`` into a LaTeX paper.

We DO NOT call an LLM here unless the user explicitly asks via
``options.synthesize=True``. Default behavior is purely deterministic — pull
metadata + cite_keys, render a templated paragraph. The user gets a clean
starting point, edits it, done.
"""

from __future__ import annotations

import datetime as dt
import io
import logging
import zipfile

from .. import config as cfg
from ..tools.bibtex_export import BibtexExportInput, _cite_key, export_bibtex
from ._common import (
    PaperBundle,
    collect_metadata,
    fetch_paper_bundle,
)
from .dispatch import DeliverableResult

log = logging.getLogger(__name__)


_RELATED_WORK_HEADER = """\
% Generated by paper_rag on {date}.
% This is a starter related-work paragraph for {n_papers} papers.
% Edit freely; the {bib_file} file goes alongside this .tex file.

"""


_LLM_PROMPT_TEMPLATE = """You are writing a LaTeX `related work' paragraph (1-2 paragraphs, ~250 words).

Below are summaries for {n} papers, each tagged with a cite_key.
Synthesize them into ONE coherent paragraph. Cite EVERY non-trivial claim
using LaTeX \\cite{{cite_key}} syntax. Do NOT invent papers.

CRITICAL:
- Output ONLY the LaTeX paragraph (no preamble, no \\begin/\\end document)
- Use only the cite_keys provided below
- DO NOT use [chunk:xxx] notation - convert to \\cite{{}} only
- One coherent paragraph or two; no section headers

Papers:
{summaries}

Output:
"""


def _format_summaries_for_latex(bundles_with_keys: list[tuple[PaperBundle, str]]) -> str:
    parts = []
    for b, key in bundles_with_keys:
        if not b.summary:
            continue
        # Strip [chunk:...] from summary so LLM doesn't get tempted to keep them
        clean = b.summary
        parts.append(f"cite_key: {key}\nTitle: {b.title}\nSummary: {clean}")
    return "\n\n---\n\n".join(parts)


def _synthesize_with_llm(bundles_with_keys: list[tuple[PaperBundle, str]]) -> str:
    """Optional LLM call to draft a related-work paragraph."""
    summaries = _format_summaries_for_latex(bundles_with_keys)
    if not summaries.strip():
        return "% No paper summaries available — synthesis skipped.\n"

    prompt = _LLM_PROMPT_TEMPLATE.format(
        n=len(bundles_with_keys), summaries=summaries,
    )
    try:
        from ..rag.llm import chat
        body = chat(
            [
                {"role": "system",
                 "content": "You write LaTeX academic prose. Strict citation discipline."},
                {"role": "user", "content": prompt},
            ],
            temperature=cfg.load().llm.temperatures.latex_bib,
            max_tokens=1500,
        )
    except Exception as e:
        log.warning("LaTeX synthesis LLM call failed: %s; falling back to template", e)
        return _template_paragraph(bundles_with_keys)
    return body.strip() + "\n"


def _template_paragraph(bundles_with_keys: list[tuple[PaperBundle, str]]) -> str:
    """Deterministic fallback: list-style paragraph, every paper cited once."""
    if not bundles_with_keys:
        return "% No papers were ingested — this section is empty.\n"

    sentences = []
    for b, key in bundles_with_keys:
        title = (b.title or "Untitled").rstrip(".")
        sentences.append(f"{title}~\\cite{{{key}}}")

    lead = "Recent work on this topic includes "
    body = ", ".join(sentences[:-1])
    last = sentences[-1]
    if len(sentences) == 1:
        para = f"{lead}{last}.\n"
    elif len(sentences) == 2:
        para = f"{lead}{sentences[0]} and {last}.\n"
    else:
        para = f"{lead}{body}, and {last}.\n"
    return para


def generate(
    paper_ids: list[str],
    *,
    title: str | None = None,
    synthesize: bool = False,
    tex_style: str = "natbib",  # currently informational; affects bib preamble comment only
    **_unused,
) -> DeliverableResult:
    """Generate a zip of references.bib + related_work.tex."""
    title = title or "Related Work Bundle"

    # Step 1: bibtex via the M6 #31 helper (unchanged)
    bib_result = export_bibtex(BibtexExportInput(paper_ids=paper_ids))
    bib_text = bib_result.get("bibtex", "")
    missing = bib_result.get("missing", [])

    # Step 2: bundle for tex synthesis (LLM optional)
    bundles_with_keys: list[tuple[PaperBundle, str]] = []
    bundles: list[PaperBundle] = []
    for pid in paper_ids:
        if pid in missing:
            continue
        b = fetch_paper_bundle(pid, run_qa=synthesize)
        bundles.append(b)
        bundles_with_keys.append((b, _cite_key(pid)))

    # Step 3: tex paragraph
    today = dt.date.today().isoformat()
    bib_filename = "references.bib"
    if synthesize:
        body = _synthesize_with_llm(bundles_with_keys)
    else:
        body = _template_paragraph(bundles_with_keys)

    header = _RELATED_WORK_HEADER.format(
        date=today, n_papers=len(bundles), bib_file=bib_filename,
    )
    tex_text = header + body
    if missing:
        tex_text += (
            "\n% NOTE: the following paper_ids were not found in the local "
            "library and were skipped:\n"
            + "\n".join(f"%   - {m}" for m in missing) + "\n"
        )

    # Step 4: zip
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(bib_filename, bib_text)
        zf.writestr("related_work.tex", tex_text)
    buf.seek(0)

    safe_title = title.lower().replace(" ", "_").replace("/", "_")[:60]
    return DeliverableResult(
        format="latex_bib",
        filename=f"{safe_title}_{today}.zip",
        content_bytes=buf.getvalue(),
        content_type="application/zip",
        metadata={
            **collect_metadata(bundles),
            "tex_style": tex_style,
            "synthesized": synthesize,
            "missing_paper_ids": missing,
            "bib_filename": bib_filename,
            "tex_filename": "related_work.tex",
        },
    )


__all__ = ["generate"]
